### PR TITLE
Specify parameters.yml location

### PR DESCRIPTION
**Pull request by sagikazarmark**
Partial resubmission of #48:
- Uses `app_config_path` variable
- Fixes conflicts

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@peterjmit what about this one?

**Comment by sagikazarmark** [comment]
ping @peterjmit

**Comment by sagikazarmark** [comment]
ping @peterjmit

**Comment by Nyholm** [comment]
Hey. Thank you very much. Sorry for the great delay.

**Comment by sagikazarmark** [comment]
Cool, thanks!

**Pull request merged**
